### ISSUE TITLE
"Loading Comments..." message always being displayed

### ISSUE THREAD

**Issue by jakeleboeuf** [sir-dunxalot/ember-disqus#10]
First load works as expected.

However, if I visit a route that envokes the `disqus-comments` component, and then navigate to a new view with another instance of the `disqus-comments`, the "Loading Comments..." text is present above the `iframe`.

<img width="793" alt="screenshot 2016-09-21 08 39 19" src="https://cloud.githubusercontent.com/assets/690573/18711277/255616ac-7fd7-11e6-877f-748af4117677.png">

**Comment by sir-dunxalot** [comment]
Fixed by #14
