### ISSUE TITLE
Incompatible with Ember CLI 2.11

### ISSUE THREAD

**Issue by lolmaus** [sir-dunxalot/ember-disqus#12]
Currently, it crashes apps based on Ember CLI 2.11 because its own Ember CLI setup is so old.

@sir-dunxalot Are you going to maintain this addon? Looks like it's been abandoned for two years.

I tried upgrading this addon's Ember CLI setup, but the tests are written in an outdated fashion, and I wasn't able to align them with modern conventions.

Please either upgade it to latest Ember CLI or consider passing it to another maintainer. I'm thinking of restarting this addon from scratch.

**Comment by lolmaus** [comment]
CC @Redsandro

**Comment by sir-dunxalot** [comment]
I've created #13 to update Ember CLI. It's not ready for merge yet because the test suite coverage isn't good enough. However, you may be able to use [sir-dunxalot/ember-disqus#ember-cli-upgrade](https://github.com/sir-dunxalot/ember-disqus/tree/ember-cli-upgrade) in the interim.

**Comment by Redsandro** [comment]
Hi @lolmaus @sir-dunxalot. Nice to see some lifesigns in here! Would love to see this updated. It's one of the reasons I stick with CLI 2.7.

I've updated #9 if it helps.

**Comment by Redsandro** [comment]
@lolmaus any updates on this?

Is there a specific `package.josn` config to get `ember-disqus` running on a more recent version of Ember, or do you need manual module trickery?

**Comment by lolmaus** [comment]
@Redsandro I'm using #9 on my website and it works. I didn't do anything about it since my previous message a month ago.

**Comment by Redsandro** [comment]
So @sir-dunxalot can safely push this as an interim version to `npm` in order to safely fix this broken package. :information_source: 

-update-

oh wait -- 

What is this?

> `0.2.1` is the latest of 4 releases
> sir-dunxalot published 3 weeks ago

Is this the compatible version with Ember 2.11?

**Comment by sir-dunxalot** [comment]
`0.2.1` releases #13, which updates the Ember CLI environment to the latest release at that time, which was `2.12.0-beta.1`.

**Comment by sir-dunxalot** [comment]
I just released `1.0.0`, which adds support for Ember 3. As such, I consider this issue  out-of-date.
