### ISSUE TITLE
disqus-comment-count

### ISSUE THREAD

**Issue by spencerwyckoff** [sir-dunxalot/ember-disqus#4]
First off, very nice plug in here... works just like you say it should.

Only minor change I would like to see so far is right now it appears the {{disuqs-comment-count}} gets the number of total comments per discussion INCLUDING deleted ones... As a discussion moderator and developer, I would like to see a comment-count of only APPROVED comments.  It appears Disqus keeps all comments made per discussion (including deleted ones) so not sure if this is even possible or if there would be a way to filter down the list to simply approved ones.

**Comment by sir-dunxalot** [comment]
I don't believe this is possible with Disqus right now. This is the only documentation I know of for [Disqus comment count](https://help.disqus.com/developer/adding-comment-count-links-to-your-home-page).

If you know otherwise, let me know and I'd be happy to make this improvement.
