### ISSUE TITLE
Placeholder text not being removed on revisit to page

### ISSUE THREAD

**Issue by kybishop** [sir-dunxalot/ember-disqus#5]
I have a `{{disqus-comments}}` on a show page. On the first visit to the show page, the placeholder "Loading Comments..." is shown, then removed once Disqus is ready. Upon going back to my index page, then revisiting the show page, the placeholder text is no longer removed, but instead sits above the Disqus comments.

I'm currently getting around this by providing an empty block as the placeholder, but this obviously isn't ideal. Sorry I couldn't be of more help and debug this myself; I took a look through the code and couldn't find the logic tied to redrawing/overwriting the template/placeholder text.

I'd be happy to dig deeper if pointed in the right direction as far as where the redrawing happens.

**Comment by sir-dunxalot** [comment]
No problem - you gave a good amount of info! I think this should be easy to fix by correctly tracking the loaded state and wrapping the placeholder in an `{{#if loaded}}` block, but I will dig into it when I can get around to it. I would happily accept a PR too.

Tbh, I haven't used this addon in a little while so it could do with a clean up all round.

**Comment by sir-dunxalot** [comment]
Fixed by #14
