### ISSUE TITLE
Overriding init without calling this._super is deprecated

### ISSUE THREAD

**Issue by Redsandro** [sir-dunxalot/ember-disqus#7]
Installing this results in the following deprecation message:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/var/www/myproject/node_modules/ember-cli/lib/models/addon.js:1009:27)
```

```
Ember      : 2.7.0
Ember Data : 2.7.0
jQuery     : 2.2.4
```

**Comment by animerumah** [comment]
Is this issue has been fixed?

Because the error still showing, and still use ember-cli-htmlbars 0.7.6
npm view ember-disqus

**Comment by sir-dunxalot** [comment]
I don't believe this has been fixed but it should be relatively easy to put out a patch for it.

**Comment by sir-dunxalot** [comment]
A PR would be great as I probably won't have the ability to get round to this this week.

**Comment by animerumah** [comment]
Well, @Redsandro has open the PR right? is something goes wrong?

**Comment by sir-dunxalot** [comment]
Sorry - I completely missed that PR (and this issue when it was originally opened. I will look at the PR now.
